function assignOnClicks(){var anchors=document.getElementsByTagName('a');var i=0;for(i=0;i<anchors.length;i++){var anchor=anchors[i];if(/slidelink/i.test(anchor.className)){anchor.onclick=function(){History.pushState({},"MS Paint Fan Adventures","?"+ this.href.split("?")[1]);return false;}}}
var buttons=document.getElementById('articleholder').getElementsByTagName('button');for(i=0;i<buttons.length;i++){var button=buttons[i];if(/spoiler/i.test(button.parentNode.className))button.onclick=function(){spoilerButtonPressed(this)};}
setTitle();onSlideLoad();}
function spoilerButtonPressed(button){if(/closed/i.test(button.parentNode.className)){button.parentNode.className="spoiler open";button.title=button.getAttribute("data-open-title");button.innerHTML=button.getAttribute("data-open-text");}else if(/open/i.test(button.parentNode.className)){button.parentNode.className="spoiler closed";button.title=button.getAttribute("data-closed-title");button.innerHTML=button.getAttribute("data-closed-text");}}
function onSlideLoad(){var txt=document.getElementById("slide").innerHTML;var patt1=/\[js=['"]?(.+?)['"]?\]/gim;var match=patt1.exec(txt);while(match!=null){var remote_script=document.createElement("script");remote_script.src=match[1];document.getElementById("slide").appendChild(remote_script);match=patt1.exec(txt);}
var patt2=/\[js\](.+?)\[\/js\]/gim;var match=patt2.exec(txt);while(match!=null){eval(match[1].replace(/<br\s*\/?>/,""));match=patt2.exec(txt);}}
function setTitle(){window.document.title=document.getElementById("pagecommand").firstChild.firstChild.firstChild.nodeValue;document.body.id=document.getElementById("savegame").className;}
function generateXMLRequest(){if(window.XMLHttpRequest)
{return new XMLHttpRequest();}
else
{return new ActiveXObject("Microsoft.XMLHTTP");}}
function displaySlide(purl){var patt=/s=(\d+)&p=(\d+)/i;var vals=patt.exec(purl);var xmlhttp=generateXMLRequest();xmlhttp.onreadystatechange=function()
{if(xmlhttp.readyState==4&&xmlhttp.status==200)
{document.getElementById("slide").innerHTML=xmlhttp.responseText;window.scrollTo(0,0);assignOnClicks();element=document.getElementById("asyncript");if(element)element.parentNode.removeChild(element);var pwr=new String(Math.random()*9999);pwr=pwr.substr(0,5);var pw_s="http://www.projectwonderful.com/gen_async.php?id=60252&type=5&location=http://mspfanventures.com/"+"&r="+ pwr;var pw_adloader=document.createElement("script");pw_adloader.src=pw_s;pw_adloader.id="asyncript";(document.getElementsByTagName("head")[0]||pw_d.getElementsByTagName("body")[0]).appendChild(pw_adloader);}}
xmlhttp.open("GET","cache/a"+vals[1]+"/p"+vals[2]+".html",true);xmlhttp.send();}
document.onkeydown=function(evt){evt=evt||window.event;var targetLink;switch(evt.keyCode){case 35:if((evt.ctrlKey)&&(nl=document.getElementById('pagelist'))){nls=nl.getElementsByTagName("a");if(nls.length>0)targetLink=nls[0];}break;case 36:if((evt.ctrlKey)&&(bl=document.getElementById('backlinks'))){bls=bl.getElementsByTagName("a");if(bls.length>2)targetLink=bls[0];}break;case 37:if(bl=document.getElementById('backlinks')){bls=bl.getElementsByTagName("a");if(bls.length>2)targetLink=bls[1];}break;case 39:if(nl=document.getElementById('nextlinks')){nls=nl.getElementsByTagName("a");if(nls.length==1)targetLink=nls[0];}break;case 48:var buttons=document.getElementById('articleholder').getElementsByTagName('button');for(i=0;i<buttons.length;i++){var button=buttons[i];if(/spoiler/i.test(button.parentNode.className))spoilerButtonPressed(button);}
return false;case 83:var savelink=document.getElementById('savegame');if(savelink)window.location=savelink.href;return false;case 76:var loadlink=document.getElementById('loadgame');if(loadlink)window.location=loadlink.href;return false;}
if(targetLink){History.pushState({},"MS Paint Fan Adventures","?"+ targetLink.href.split("?")[1]);return false;}};(function(window,undefined){var History=window.History;if(!History.enabled){return false;}
History.Adapter.bind(window,'statechange',function(){var State=History.getState();displaySlide("?"+ State.url.split("?")[1]);});})(window);